// samples/spa-react-minimal/src/app/component/CustomArea.js
import React from 'react';
import { EditableArea, EditableComponent } from '@magnolia/react-editor';

class CustomArea extends EditableArea {
  render() {
    const { content } = this.props;
    const componentNames = content['@nodes'];
    const hasComponents = componentNames.length > 0;
    return (
      <div ref={node => (this.node = node)} key={content['@id']}>
        <p>
          Custom area script:
          {content.title}
        </p>
        {hasComponents ? (
          <EditableComponent
            key={content[componentNames[0]]['@id']}
            content={content[componentNames[0]]}
          />
        ) : null}
      </div>
    );
  }
}

export default CustomArea;

// samples/spa-angular-minimal/src/app/components/custom-area.component.ts
import { Component, Input } from '@angular/core';
import { EditableArea } from '@magnolia/angular-editor';

@Component({
  selector: '[custom-area]',
  template: `
    <div class="container">
      <div class="row">
        <ng-template ngFor let-component [ngForOf]="components">
          <editable-component [content]="component" class="col-sm-4"></editable-component>
        </ng-template>
      </div>
    </div>
  `
})
export class CustomArea extends EditableArea {
}
