// src/app/components/textImage.component.ts
import { Component, Input } from '@angular/core';
import { environment } from '../../environments/environment';

@Component({
  template: `
    <div>
      <h3>{{title}}</h3>
      <div class="body" [innerHTML]="body">
      </div>
      <img class="img-responsive" [src]="imageLink" alt="" *ngIf="imageLink" />
    </div>
  `,
    styles: ['.body { font-size: small; word-wrap: break-word; }']
})
export class TextImageComponent {
  @Input() title: string;
  @Input() body: string;

  @Input() set image(image: object) {
    this.imageLink = environment.server + image['renditions']['480'].link;
  }

  imageLink: string = null;
}

// samples/spa-react-minimal/src/app/component/TextImage.js
import React from 'react';
import PropTypes from 'prop-types';
import ENVIRONMENT from '../../environments/environment';

function TextImage(props) {
    const { title, image, text } = props;

    function CleanImage(properties) {
        const { image: img } = properties;
        if (img && img.renditions) {
            const damURL = ENVIRONMENT.server + img.renditions['480'].link;

            return (
                <img className="img-responsive" src={damURL} alt="TextIm alt." />
            );
        }
        return null;
    }

    function createMarkup() {
        return { __html: text };
    }

    return (
        <div>
            <h5 className="light">{title}</h5>
            <div>
                <CleanImage image={image} />
            </div>
            <div>
                <p dangerouslySetInnerHTML={createMarkup()} />
            </div>
        </div>
    );
}

TextImage.propTypes = {
    title: PropTypes.string,
    image: PropTypes.object,
    text: PropTypes.string
};

TextImage.defaultProps = {
    title: null,
    image: null,
    text: null
};

export default TextImage;
